# yaml-language-server: $schema=https://raw.githubusercontent.com/mfontanini/presenterm/master/config-file-schema.json
defaults:
  theme: catppuccin-latte
  terminal_font_size: 16
options:
  implicit_slide_ends: true
  strict_front_matter_parsing: false
export:
  dimensions:
    columns: 80
    rows: 30
