# yaml-language-server: $schema=https://raw.githubusercontent.com/mfontanini/presenterm/master/config-file-schema.json
defaults:
  theme: gruvbox-dark
options:
  implicit_slide_ends: true
  strict_front_matter_parsing: false
export:
  pauses: new_slide
